/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface WebviewOptions {
  title?: string | undefined | null
  debug?: boolean | undefined | null
  content?: string | undefined | null
  width: number
  height: number
}
export function createWindow(options: WebviewOptions): void
